# Generated by Django 3.0.7 on 2022-09-01 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('participant', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(null=True)),
                ('chat_thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat', to='chat.UserChatThread')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
