# Generated by Django 3.0.7 on 2022-09-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatthread',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
