# Generated by Django 3.0.7 on 2022-09-01 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20220901_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatthread',
            name='participant',
            field=models.ManyToManyField(null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
