# Generated by Django 3.0.7 on 2022-09-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220901_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatthread',
            name='likes',
        ),
    ]
