# Generated by Django 3.0.7 on 2022-09-01 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_userchatthread_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatthread',
            name='participant',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
