# Generated by Django 4.1 on 2022-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_auto_20220901_1254"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchat",
            name="is_seen",
        ),
        migrations.RemoveField(
            model_name="userchat",
            name="seen_at",
        ),
        migrations.AddField(
            model_name="userchat",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
